version: "3.8"

services:
  products_api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    working_dir: /code/
    volumes:
      - .:/code
    command: sh -c "python app"
    environment:
      PYTHONPATH: "/code/"
