apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-api
  template:
    metadata:
      labels:
        app: products-api
    spec:
      containers:
        - image: lan123/rso-projekt:products
          imagePullPolicy: "Always"
          name: products-api
          env:
            - name: CONSUL_HOST
              value: 20.23.218.60
          ports:
            - containerPort: 8000
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/products/health/live/
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /api/v1/products/health/ready/
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: products-api
spec:
  type: ClusterIP
  ports:
    - port: 8000
      protocol: TCP
      targetPort: server
  selector:
    app: products-api