apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-api
  template:
    metadata:
      labels:
        app: products-api
    spec:
      containers:
        - image: lan123/rso-projekt:products
          imagePullPolicy: "Always"
          name: products-api
          ports:
            - containerPort: 8000
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: products-api
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      protocol: TCP
      targetPort: server
  selector:
    app: products-api